try {
    throw new Error('There was an error.');
} catch (err) {
    console.log(err);
}